name: Build Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ImageBuild:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          version: latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: TARGETOS=linux
          tags: |
            ghcr.io/walnuts1018/kubebuilder-devcontainer-image:latest
            ghcr.io/walnuts1018/kubebuilder-devcontainer-image:v0.0.${{ github.run_number }}
