name: Build Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ImageBuild:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          version: latest

      - name: Build and push Docker images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: TARGETOS=linux
          tags: |
            ghcr.io/walnuts1018/kubebuilder-devcontainer-image:latest
            ghcr.io/walnuts1018/kubebuilder-devcontainer-image:v0.0.${{ github.run_number }}
