name: Build Docker Image
on:
  release:
    types: [published]

jobs:
  ImageBuild:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Get Tag from Release
        run: echo "ImageTag=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: TARGETOS=linux
          tags: |
            ghcr.io/walnuts1018/kubebuilder-devcontaner-image:latest
            ghcr.io/walnuts1018/kubebuilder-devcontaner-image:${{ github.event.release.tag_name }}
